#
# This file is part of the NML build framework
# NML build framework is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
# NML build framework is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with NML build framework. If not, see <http://www.gnu.org/licenses/>.
#

# Definition of the grfs
REPO_NAME           ?= Japanese Buildings

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= jpbuildmod

# Documentation files
# DOC_FILES ?= docs/readme.txt docs/license.txt docs/changelog.txt
DOC_FILES := doc/license.txt

# Possible offset to NewGRF version. Increase by one, if a release
# branch is added to the repository
REPO_BRANCH_VERSION ?= 0

# Directory structure
SCRIPT_DIR          ?= scripts

GENERATE_GRF := nfo
NFO_FILE     := $(BASE_FILENAME).nfo
NML_FILE     := $(BASE_FILENAME).nfo
MAIN_SRC_FILE:= $(BASE_FILENAME)d.hnfo  #USE DOS MAKE for Palette

NML          := grfcodec
NML_FLAGS    := -em 1

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
# GFX_SCRIPT_LIST_FILES      := gfx/png_source_list

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.3
# MIN_NML_REVISION     = 0
